---
###
### collector RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: collector
  namespace: {{.Values.namespace}}
  labels:
    component: collector
    namespace: {{.Values.namespace}}
---
###
### jaeger RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: jaeger
  namespace: {{.Values.namespace}}
  labels:
    component: jaeger
    namespace: {{.Values.namespace}}